services:
  - type: web
    name: imtahan-sistemi
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        value: mongodb+srv://nahedshukurlu_db_user:EebPHBmTA12QOD03@exam-result.bjiyluu.mongodb.net/imtahan_db?retryWrites=true&w=majority
    healthCheckPath: /
    autoDeploy: true

databases:
  - name: imtahan-db
    plan: free
    databaseName: imtahan
    user: imtahan_user
